// Complete Tailwind class strings stay here so the UI components stay readable.
// Tailwind scans this file automatically; avoid constructing partial class names.
export const sessionStyles = {
  tabs: "flex flex-wrap gap-2 border-b border-line pb-3",
  tab: "min-h-11 rounded-md px-4 py-2 text-sm font-semibold text-muted hover:bg-paper aria-selected:bg-gold aria-selected:text-black focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold",
  controlPanel: "rounded-lg border border-line bg-white p-4",
  managementSection: "mt-5 border-t border-line pt-4",
  scheduleItem: "mt-3 border-b border-line py-3",
  defaultFields: "my-4 space-y-3",
  defaultField: "grid items-center gap-2 text-sm sm:grid-cols-2",

  pageHeading: "page-heading",
  eyebrow: "eyebrow",
  section: "space-y-5",
  weekToolbar: "flex flex-wrap items-center justify-between gap-4",
  weekTitle: "text-xl",
  help: "mt-2 text-xs text-muted",
  weekNavigation: "flex flex-wrap gap-2",
  error: "form-error",
  emptyState: "rounded-xl border border-line bg-white px-5 py-12 text-center",
  emptyTitle: "text-lg",
  emptyDescription: "mt-3 text-sm text-muted",
  sessionActions: "flex flex-wrap items-start gap-4",
  updateSummary: "cursor-pointer py-3 text-xs underline",
  timeFields: "grid gap-3 sm:grid-cols-2",
  managementSummary: "cursor-pointer text-muted",
  managementList:
    "mt-3 divide-y divide-line rounded-md border border-line bg-white px-4",
  managementItem: "flex flex-wrap items-center justify-between gap-3 py-1",
  boardHelp: "text-xs leading-relaxed text-muted",
  boardScroll:
    "relative overflow-x-auto border border-[#b8dce8] bg-[#f2f2f2] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-gold",
  table: "w-full border-collapse text-left text-sm text-black",
  srOnly: "sr-only",
  headerRow: "bg-[#94dcf4]",
  corner: "sticky left-0 z-10 w-40 min-w-36 bg-[#94dcf4] px-3 py-2",
  sessionHeader: "min-w-44 px-3 py-2 text-center text-lg font-bold",
  sessionTime: "mt-1 whitespace-nowrap",
  row: "h-11",
  nameCell:
    "sticky left-0 z-10 h-11 bg-[#caedfa] px-3 py-0 text-lg font-normal",
  name: "block max-w-44 truncate",
  youLabel: "ml-1 text-xs text-[#20516b]",
  responseCell: "h-11 p-0 align-top",
  countRow: "border-t border-[#b8dce8] bg-[#eaf7fc] text-xs text-[#20516b]",
  countLabel: "sticky left-0 z-10 bg-[#eaf7fc] px-3 py-2 font-medium",
  count: "px-3 py-2 text-center",
  formError: "mt-3 text-xs text-red-800",
  formSuccess: "mt-3 text-xs text-green",
  addPanel: "rounded-xl border border-line bg-white p-5",
  addSummary: "cursor-pointer font-semibold",
  addForm: "mt-4",
  fields: "grid gap-4 sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-end",
  fieldLabel: "text-xs font-semibold",
  addButton: "min-h-11 rounded-md bg-gold px-4 py-2 font-semibold",
  removeButton: "min-h-11 text-xs font-normal text-red-800 underline",
  legend: "flex flex-wrap gap-x-5 gap-y-2 text-xs",
  legendItem: "flex items-center gap-2",
  option: "bg-white text-black",
  pending: "text-muted",
  saveError: "text-red-800",
  saved: "text-green",
  navigationLink:
    "inline-flex min-h-11 items-center justify-center rounded-md border border-line bg-white px-3 text-sm hover:bg-paper",
  input:
    "mt-2 min-h-11 w-full rounded-md border border-line bg-white px-3 py-2 text-sm",
  legendSwatch: "size-4 border border-black/10",
  readOnlyResponse: "flex h-11 items-center justify-center px-2 text-xs",
  responseSelect:
    "h-11 w-full cursor-pointer rounded-none border-0 px-3 text-center text-sm font-medium focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-[#20516b] disabled:cursor-wait",
  cellError: "bg-white px-2 py-1 text-xs",
} as const;

export const responseStyles = {
  yes: "bg-[#00b050] text-black",
  maybe: "bg-[#ffff00] text-black",
  no: "bg-[#c00000] text-white",
  "": "bg-[#f2f2f2] text-[#595959]",
} as const;
